# Generated by Django 5.2.16 on 2026-08-13 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0013_tripstatusevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('PENDING', 'Pending'), ('WAITING_PAYMENT', 'Awaiting Payment'), ('CONFIRMED', 'Confirmed'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('PARTIAL_PAYMENT', 'Partial Payment'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('WAITING_PAYMENT', 'Awaiting Payment'), ('CONFIRMED', 'Confirmed'), ('READY', 'Ready'), ('COMPLETED', 'Completed'), ('PARTIAL_PAYMENT', 'Partial Payment'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('reason', models.CharField(blank=True, default='', help_text="Optional context for the change, e.g. 'advance payment received'.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='django_trips.tripbooking')),
                ('changed_by', models.ForeignKey(blank=True, help_text='Staff user who made this change; blank means system/automatic.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_status_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
