# Generated by Django 5.2.17 on 2026-09-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0015_alter_location_fks_to_use_swappable_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('CHALLENGING', 'Challenging')], default='', help_text='How physically demanding this trip is. Blank means unrated.', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_private',
            field=models.BooleanField(default=False, help_text='This trip runs for one booking party only, never as a shared departure.'),
        ),
    ]
