# Generated by Django 5.2.17 on 2026-09-25 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0016_trip_difficulty_is_private'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.DJANGO_TRIPS_LOCATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, help_text='Public reference, e.g. CT-482193. The prefix comes from the DJANGO_TRIPS_CUSTOM_TRIP_REFERENCE_PREFIX setting.', max_length=20, unique=True)),
                ('region_note', models.CharField(blank=True, default='', max_length=255)),
                ('duration', models.CharField(choices=[('4_5', '4-5 days'), ('6_7', '6-7 days'), ('8_10', '8-10 days')], max_length=10)),
                ('date_mode', models.CharField(choices=[('MONTH', 'A month or season'), ('EXACT', 'Exact dates')], max_length=10)),
                ('target_month', models.DateField(blank=True, help_text='First day of the month, in MONTH mode.', null=True)),
                ('month_precision', models.CharField(blank=True, choices=[('MONTH', 'Month'), ('SEASON', 'Season')], default='', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('children_ages', models.JSONField(blank=True, default=list)),
                ('infants', models.PositiveSmallIntegerField(default=0)),
                ('transport', models.CharField(choices=[('PRIVATE_DRIVER', 'Private car and driver'), ('SELF_DRIVE', 'Driving themselves'), ('OWN_WAY', 'Reaching the region themselves')], max_length=20)),
                ('pickup_point', models.CharField(blank=True, default='', max_length=255)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('meals', models.CharField(choices=[('BREAKFAST_DINNER', 'Breakfast and dinner'), ('BREAKFAST', 'Breakfast only'), ('EAT_OUT', 'Eating out')], max_length=20)),
                ('food_preferences', models.JSONField(blank=True, default=list)),
                ('food_note', models.CharField(blank=True, default='', max_length=255)),
                ('pace', models.CharField(choices=[('EASY', 'Easy'), ('BALANCED', 'Balanced'), ('PACKED', 'Packed')], max_length=10)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('DRAFTING', 'Drafting'), ('DRAFTED', 'Drafted'), ('FAILED', 'Failed')], default='DRAFTING', max_length=10)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('plan', models.JSONField(blank=True, null=True)),
                ('estimate_min', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('estimate_max', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drafted_at', models.DateTimeField(blank=True, null=True)),
                ('region', models.ForeignKey(blank=True, help_text='Where the traveler wants to go. Empty when they typed a place into `region_note` instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.DJANGO_TRIPS_LOCATION_MODEL)),
                ('source_trips', models.ManyToManyField(blank=True, related_name='+', to='django_trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='django_trip_user_id_a7c09b_idx')],
            },
        ),
    ]
