# Generated by Django 5.2.17 on 2026-09-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_trips', '0017_customtrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtrip',
            name='custom_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many days, when `duration` is CUSTOM. At most DJANGO_TRIPS_CUSTOM_TRIP_MAX_DAYS.', null=True),
        ),
        migrations.AlterField(
            model_name='customtrip',
            name='duration',
            field=models.CharField(choices=[('1', 'Day trip'), ('2_3', '2-3 days'), ('4_5', '4-5 days'), ('6_7', '6-7 days'), ('8_10', '8-10 days'), ('CUSTOM', 'A set number of days')], max_length=10),
        ),
    ]
